# GitHub Actions Workflow created for handling the release process based on the draft release prepared with the Build workflow.
# Running the publishPlugin task requires all following secrets to be provided: PUBLISH_TOKEN, PRIVATE_KEY, PRIVATE_KEY_PASSWORD, CERTIFICATE_CHAIN.
# See https://plugins.jetbrains.com/docs/intellij/plugin-signing.html for more information.

name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Build Plugin
        run: |
          ./gradlew buildPlugin         
          PKG="$(basename ${{ github.repository }})-${{ github.ref_name }}.zip"
          mv build/distributions/*.zip $PKG
          gh release create ${{ github.ref_name }} "./build/distributions/$PKG" --generate-notes